from . import res_users
from . import voiture
from . import marque
from . import modele
from . import assurance
from . import carte_grise
from . import contrat_location
from . import employe
from . import entretien
from . import affectation
from . import carburant
from . import document
from . import client
from . import dashboard  